2021-09-10 21:09:59,421UTC: WARNING:root:Script C:/Users/Rob/source/repos/Automation/labs/lab_utils.py cannot be run independently from this application.
2021-09-10 21:10:54,400UTC: WARNING:root:Script C:/Users/Rob/source/repos/Automation/labs/lab_utils.py cannot be run independently from this application.
2021-09-10 21:33:20,408UTC: WARNING:root:Script /home/gns3demo/Automation/labs/lab_utils.py cannot be run independently from this application.
2021-09-11 16:19:57,877UTC: WARNING:root:Script C:/Users/Rob/source/repos/Automation/labs/lab_utils.py cannot be run independently from this application.
2021-09-11 16:20:37,173UTC: WARNING:root:Script C:/Users/Rob/source/repos/Automation/labs/lab_utils.py cannot be run independently from this application.
2021-09-23 14:59:54,746UTC: CRITICAL:root:
Type RuntimeError: Unable to execute command: [sudo] password for gns3user: 
Sorry, try again.
[sudo] password for gns3user: 
Sorry, try again.
[sudo] password for gns3user: 
sudo: 3 incorrect password attempts
 in /home/gns3user/Automation/labs/test.py at line 37.

2021-09-23 15:03:05,434UTC: CRITICAL:root:
Type RuntimeError: Unable to execute command:  in /home/gns3user/Automation/labs/test.py at line 37.

2021-09-23 15:04:49,637UTC: CRITICAL:root:
Type TypeError: string indices must be integers, not str in /home/gns3user/Automation/labs/test.py at line 38.

2021-09-23 15:05:52,009UTC: CRITICAL:root:
Type RuntimeError: Unable to execute command:  in /home/gns3user/Automation/labs/test.py at line 38.

2021-09-23 15:06:40,283UTC: CRITICAL:root:
Type RuntimeError: Unable to execute command:  in /home/gns3user/Automation/labs/test.py at line 38.

2021-09-23 15:08:18,693UTC: CRITICAL:root:
Type RuntimeError: Unable to execute command: sudo: 3 incorrect password attempts in /home/gns3user/Automation/labs/test.py at line 38.

2021-09-23 15:21:53,085UTC: CRITICAL:root:
Type RuntimeError: Unable to execute command: [sudo] password for gns3user: 
Sorry, try again.
[sudo] password for gns3user: 
Sorry, try again.
[sudo] password for gns3user: 
sudo: 3 incorrect password attempts in /home/gns3user/Automation/labs/test.py at line 38.

2021-09-23 15:23:02,216UTC: CRITICAL:root:
Type RuntimeError: Unable to execute command: sudo mkdir --parents /var/lib/tftpboot: [sudo] password for gns3user: 
Sorry, try again.
[sudo] password for gns3user: 
Sorry, try again.
[sudo] password for gns3user: 
sudo: 3 incorrect password attempts in /home/gns3user/Automation/labs/test.py at line 37.

2021-09-23 17:39:08,304UTC: CRITICAL:root:
Type TIMEOUT: Expected "success", found Sorry, try again. in /home/gns3user/Automation/labs/lab000-combo.py at line 85.

2021-09-23 17:40:23,511UTC: WARNING:root:Script /home/gns3user/Automation/labs/lab_utils.py cannot be run independently from this application.
2021-09-23 17:40:38,594UTC: CRITICAL:root:
Type TypeError: object of type 'NoneType' has no len() in /home/gns3user/Automation/labs/lab000-combo.py at line 92.

2021-09-23 17:46:01,439UTC: CRITICAL:root:
Type RuntimeError: Cannot connect to console port. Ensure device is started or reloaded. in /home/gns3user/Automation/labs/lab000-combo.py at line 95.

2021-09-23 17:49:26,774UTC: CRITICAL:root:
Type KeyboardInterrupt:  in /home/gns3user/Automation/labs/lab000-combo.py at line 94.

2021-09-23 17:54:09,035UTC: CRITICAL:root:
Type RuntimeError: Cannot connect to console port. Ensure device is started or reloaded. in /home/gns3user/Automation/labs/lab000-combo.py at line 95.

2021-09-23 17:54:45,448UTC: CRITICAL:root:
Type RuntimeError: Cannot connect to console port. in /home/gns3user/Automation/labs/lab000-combo.py at line 95.

2021-09-23 17:57:46,356UTC: CRITICAL:root:
Type KeyboardInterrupt:  in /home/gns3user/Automation/labs/lab000-combo.py at line 90.

2021-09-23 18:00:19,905UTC: CRITICAL:root:
Type TypeError: 'NoneType' object is not iterable in /home/gns3user/Automation/labs/lab000-combo.py at line 90.

2021-09-23 18:02:04,033UTC: CRITICAL:root:
Type KeyboardInterrupt:  in /home/gns3user/Automation/labs/lab000-combo.py at line 94.

2021-09-23 18:05:19,611UTC: CRITICAL:root:
Type TIMEOUT: Expected "R1>", found "" in /home/gns3user/Automation/labs/lab000-combo.py at line 114.

2021-09-23 18:08:38,481UTC: CRITICAL:root:
Type TIMEOUT: Expected "R1>", found "" in /home/gns3user/Automation/labs/lab000-combo.py at line 329.

2021-09-23 18:13:50,295UTC: CRITICAL:root:
Type TypeError: 'NoneType' object is not iterable in /home/gns3user/Automation/labs/lab000-combo.py at line 90.

2021-09-23 18:16:33,856UTC: CRITICAL:root:
Type KeyboardInterrupt:  in /home/gns3user/Automation/labs/lab000-combo.py at line 90.

2021-09-23 18:17:00,362UTC: CRITICAL:root:
Type KeyboardInterrupt:  in /home/gns3user/Automation/labs/lab000-combo.py at line 90.

2021-09-23 18:17:43,448UTC: CRITICAL:root:
Type KeyboardInterrupt:  in /home/gns3user/Automation/labs/lab000-combo.py at line 91.

2021-09-23 18:29:43,438UTC: CRITICAL:root:
Type ValueError: Single '}' encountered in format string in /home/gns3user/Automation/labs/lab000-combo.py at line 154.

2021-09-23 21:11:35,188UTC: CRITICAL:root:
Type TIMEOUT: Expected "R1>", found "" in /home/gns3user/Automation/labs/lab000-combo.py at line 335.

2021-09-23 21:57:05,843UTC: CRITICAL:root:
Type TIMEOUT: Expected "R1>", found "" in lab000-combo.py at line 118.

2021-09-23 21:59:45,754UTC: CRITICAL:root:
Type TIMEOUT: Expected "R1>", found "" in lab000-combo.py at line 335.

2021-09-23 22:02:21,084UTC: CRITICAL:root:
Type TIMEOUT: Expected "R1>", found "" in lab000-combo.py at line 118.

2021-09-27 18:29:35,298UTC: CRITICAL:root:
Type RuntimeError: Cannot connect to console port. in /home/gns3user/Automation/labs/lab000-combo.py at line 99.

2021-09-27 18:33:07,839UTC: CRITICAL:root:
Type KeyboardInterrupt:  in /home/gns3user/Automation/labs/lab000-combo.py at line 86.

2021-09-27 20:50:13,400UTC: WARNING:root:Script /home/gns3user/Automation/labs/lab_utils.py cannot be run independently from this application.
2021-09-27 21:10:15,551UTC: CRITICAL:root:
Type IndexError: list index out of range in /home/gns3user/Automation/labs/test.py at line 70.

2021-09-27 21:13:09,572UTC: CRITICAL:root:
Type IndexError: list index out of range in /home/gns3user/Automation/labs/test.py at line 70.

2021-09-27 21:13:52,941UTC: CRITICAL:root:
Type IndexError: list index out of range in /home/gns3user/Automation/labs/test.py at line 70.

2021-09-27 21:15:15,789UTC: CRITICAL:root:
Type TypeError: 'NoneType' object has no attribute '__getitem__' in /home/gns3user/Automation/labs/test.py at line 70.

2021-09-27 21:22:24,713UTC: CRITICAL:root:
Type IndexError: list index out of range in /home/gns3user/Automation/labs/test.py at line 70.

2021-09-27 21:22:48,766UTC: CRITICAL:root:
Type IndexError: list index out of range in /home/gns3user/Automation/labs/test.py at line 70.

2021-09-27 21:34:33,046UTC: CRITICAL:root:
Type IndexError: list index out of range in /home/gns3user/Automation/labs/test.py at line 70.

2021-09-27 21:41:49,653UTC: CRITICAL:root:
Type IndexError: list index out of range in /home/gns3user/Automation/labs/test.py at line 71.

2021-09-27 21:41:57,359UTC: CRITICAL:root:
Type IndexError: list index out of range in /home/gns3user/Automation/labs/test.py at line 71.

2021-09-27 21:44:44,363UTC: CRITICAL:root:
Type IndexError: list index out of range in /home/gns3user/Automation/labs/test.py at line 72.

2021-09-27 21:51:38,678UTC: CRITICAL:root:
Type TypeError: expand() takes exactly one argument (0 given) in /home/gns3user/Automation/labs/test.py at line 71.

2021-09-27 22:07:28,668UTC: CRITICAL:root:
Type TIMEOUT: Expected re.compile(".+"), found "" in /home/gns3user/Automation/labs/lab000-combo.py at line 122.

2021-09-27 22:10:47,522UTC: CRITICAL:root:
Type TIMEOUT: Expected re.compile(".+"), found "" in /home/gns3user/Automation/labs/lab000-combo.py at line 122.

2021-09-27 22:27:50,202UTC: CRITICAL:root:
Type TIMEOUT: Expected EOF, found "OS Software, 3700 Software (C3745-ADVENTERPRISEK9-M), Version 12.4(25d), RELEASE SOFTWARE (fc1)" in /home/gns3user/Automation/labs/lab000-combo.py at line 124.

2021-09-27 22:29:01,049UTC: CRITICAL:root:
Type TIMEOUT: Expected EOF, found "OS Software, 3700 Software (C3745-ADVENTERPRISEK9-M), Version 12.4(25d), RELEASE SOFTWARE (fc1)" in /home/gns3user/Automation/labs/lab000-combo.py at line 124.

2021-09-27 22:35:16,748UTC: CRITICAL:root:
Type TypeError: not all arguments converted during string formatting in /home/gns3user/Automation/labs/lab000-combo.py at line 125.

2021-09-27 22:35:52,773UTC: CRITICAL:root:
Type TypeError: not all arguments converted during string formatting in /home/gns3user/Automation/labs/lab000-combo.py at line 125.

2021-09-27 22:42:51,398UTC: CRITICAL:root:
Type TIMEOUT: Expected "oftware, found "OS Software, 3700 Software (C3745-ADVENTERPRISEK9-M), Version 12.4(25d), RELEASE SOFTWARE (fc1)" in /home/gns3user/Automation/labs/lab000-combo.py at line 124.

2021-09-27 22:53:53,376UTC: CRITICAL:root:
Type TIMEOUT: Expected re.compile("[Ss]oftware"), found "" in /home/gns3user/Automation/labs/lab000-combo.py at line 125.

2021-09-27 22:54:57,424UTC: CRITICAL:root:
Type TIMEOUT: Expected re.compile("[Ss]oftware"), found "ftware ; Version" in /home/gns3user/Automation/labs/lab000-combo.py at line 125.

2021-09-27 23:09:10,936UTC: CRITICAL:root:
Type TIMEOUT: Expected EOF, found ".986: %SYS-5-CONFIG_I: Configured from console by console" in /home/gns3user/Automation/labs/lab000-combo.py at line 122.

2021-09-27 23:15:12,515UTC: CRITICAL:root:
Type TypeError: 'str' object is not callable in /home/gns3user/Automation/labs/lab000-combo.py at line 121.

2021-09-27 23:43:04,114UTC: CRITICAL:root:
Type TIMEOUT: Expected "success", found "Sorry, try again." in /home/gns3user/Automation/labs/lab000-combo.py at line 88.

2021-09-29 16:26:11,522UTC: CRITICAL:root:
Type TIMEOUT: Expected re.compile("include [IOSios] [Ss]oftware"), found "OS Software, 3700 Software (C3745-ADVENTERPRISEK9-M), Version 12.4(25d), RELEASE SOFTWARE (fc1)" in /home/gns3user/Automation/labs/lab000-combo.py at line 134.

2021-09-29 16:28:24,936UTC: CRITICAL:root:
Type TIMEOUT: Expected re.compile("include [IOSios] [Ss]oftware"), found "OS Software, 3700 Software (C3745-ADVENTERPRISEK9-M), Version 12.4(25d), RELEASE SOFTWARE (fc1)" in /home/gns3user/Automation/labs/lab000-combo.py at line 134.

2021-09-29 16:42:46,509UTC: CRITICAL:root:
Type TIMEOUT: Expected EOF, found "OS Software, 3700 Software (C3745-ADVENTERPRISEK9-M), Version 12.4(25d), RELEASE SOFTWARE (fc1)" in /home/gns3user/Automation/labs/lab000-combo.py at line 135.

2021-09-29 16:50:27,672UTC: CRITICAL:root:
Type TIMEOUT: Expected EOF, found "OS Software, 3700 Software (C3745-ADVENTERPRISEK9-M), Version 12.4(25d), RELEASE SOFTWARE (fc1)" in /home/gns3user/Automation/labs/lab000-combo.py at line 135.

2021-09-29 17:05:19,506UTC: CRITICAL:root:
Type TIMEOUT: Expected EOF, found "OS Software, 3700 Software (C3745-ADVENTERPRISEK9-M), Version 12.4(25d), RELEASE SOFTWARE (fc1)" in /home/gns3user/Automation/labs/lab000-combo.py at line 136.

2021-09-29 17:26:43,266UTC: CRITICAL:root:
Type TIMEOUT: Expected EOF, found "OS Software, 3700 Software (C3745-ADVENTERPRISEK9-M), Version 12.4(25d), RELEASE SOFTWARE (fc1)" in /home/gns3user/Automation/labs/lab000-combo.py at line 134.

2021-09-29 17:48:37,406UTC: CRITICAL:root:
Type TIMEOUT: Expected "subcommands, found " unable to find computer address" in /home/gns3user/Automation/labs/lab000-combo.py at line 132.

2021-09-29 17:50:33,362UTC: CRITICAL:root:
Type TIMEOUT: Expected "subcommands, found "le to find computer address" in /home/gns3user/Automation/labs/lab000-combo.py at line 133.

2021-09-29 18:25:07,971UTC: CRITICAL:root:
Type TIMEOUT: Expected "R1#, found "5/5), round-trip min/avg/max = 32/34/36 ms" in /home/gns3user/Automation/labs/lab000-combo.py at line 135.

2021-09-29 18:34:56,039UTC: CRITICAL:root:
Type TIMEOUT: Expected "R1#, found "5/5), round-trip min/avg/max = 32/35/40 ms" in /home/gns3user/Automation/labs/lab000-combo.py at line 129.

2021-09-29 19:00:56,414UTC: CRITICAL:root:
Type TIMEOUT: Expected "R1#, found "ent (5/5), round-trip min/avg/max = 32/32/36 ms" in /home/gns3user/Automation/labs/lab000-combo.py at line 129.

2021-09-29 19:01:38,546UTC: CRITICAL:root:
Type IndexError: list index out of range in /home/gns3user/Automation/labs/lab000-combo.py at line 132.

2021-09-29 19:05:48,439UTC: CRITICAL:root:
Type KeyboardInterrupt:  in /home/gns3user/Automation/labs/lab000-combo.py at line 133.

2021-09-29 19:07:08,958UTC: CRITICAL:root:
Type KeyboardInterrupt:  in /home/gns3user/Automation/labs/lab000-combo.py at line 133.

2021-09-29 19:08:00,524UTC: CRITICAL:root:
Type RuntimeError: Cannot connect to console port. in /home/gns3user/Automation/labs/lab000-combo.py at line 104.

2021-09-29 19:08:48,387UTC: CRITICAL:root:
Type RuntimeError: Cannot connect to console port. in /home/gns3user/Automation/labs/lab000-combo.py at line 104.

2021-09-29 19:11:20,610UTC: CRITICAL:root:
Type TIMEOUT: Expected "R1#, found "" in /home/gns3user/Automation/labs/lab000-combo.py at line 129.

2021-09-29 19:16:12,109UTC: CRITICAL:root:
Type KeyboardInterrupt:  in /home/gns3user/Automation/labs/lab000-combo.py at line 133.

2021-09-29 19:30:58,733UTC: CRITICAL:root:
Type RuntimeError: Cannot get the device's name. in /home/gns3user/Automation/labs/lab000-combo.py at line 144.

2021-09-29 19:33:57,189UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's name." in /home/gns3user/Automation/labs/lab000-combo.py at line 144.

2021-09-29 20:54:34,919UTC: CRITICAL:root:
Type IndexError: "list index out of range" in /home/gns3user/Automation/labs/lab000-combo.py at line 149.

2021-09-30 00:46:14,726UTC: CRITICAL:root:
Type RuntimeError: "Unable to sudo systemctl start tftp: sudo: no tty present and no askpass program specified" in /home/gns3user/Automation/labs/lab000-combo.py at line 269.

2021-09-30 15:11:18,524UTC: CRITICAL:root:
Type TypeError: "__prompt_for_password() takes no arguments (1 given)" in /home/gns3user/Automation/labs/test.py at line 240.

2021-09-30 15:15:52,713UTC: CRITICAL:root:
Type RuntimeError: "Unable to sudo systemctl stop tftp: sudo: no tty present and no askpass program specified" in /home/gns3user/Automation/labs/test.py at line 64.

2021-09-30 15:51:59,425UTC: CRITICAL:root:
Type ExceptionPexpect: "The command was not found or was not executable: booga." in /home/gns3user/Automation/labs/test.py at line 219.

2021-09-30 15:57:28,943UTC: CRITICAL:root:
Type RuntimeError: "Unable to systemctl stop tftp: Failed to stop tftp.service: Access denied
See system logs and 'systemctl status tftp.service' for details.
Warning: Stopping tftp.service, but it can still be activated by:
  tftp.socket" in /home/gns3user/Automation/labs/test.py at line 64.

2021-09-30 18:05:55,481UTC: CRITICAL:root:
Type RuntimeError: "Cannot download startup-config from device using TFTP." in /home/gns3user/Automation/labs/lab000-combo.py at line 283.

2021-09-30 18:13:31,761UTC: CRITICAL:root:
Type RuntimeError: "Cannot download startup-config from device using TFTP." in /home/gns3user/Automation/labs/lab000-combo.py at line 283.

2021-09-30 18:20:40,877UTC: CRITICAL:root:
Type RuntimeError: "Cannot download startup-config from device using TFTP." in /home/gns3user/Automation/labs/lab000-combo.py at line 283.

2021-09-30 18:47:07,856UTC: CRITICAL:root:
Type RuntimeError: "Unable to sudo systemctl stop tftp: sudo: no tty present and no askpass program specified" in /home/gns3user/Automation/labs/test.py at line 71.

2021-09-30 18:51:43,028UTC: CRITICAL:root:
Type RuntimeError: "Unable to sudo systemctl stop tftp: sudo: no tty present and no askpass program specified" in /home/gns3user/Automation/labs/test.py at line 71.

2021-09-30 18:54:25,965UTC: CRITICAL:root:
Type RuntimeError: "Unable to sudo systemctl stop tftp: sudo: no tty present and no askpass program specified" in /home/gns3user/Automation/labs/test.py at line 73.

2021-09-30 18:59:27,858UTC: CRITICAL:root:
Type RuntimeError: "Unable to sudo firewall-cmd --zone=public --add-service=tftp: sudo: no tty present and no askpass program specified" in /home/gns3user/Automation/labs/test.py at line 58.

2021-09-30 18:59:45,297UTC: CRITICAL:root:
Type RuntimeError: "Unable to sudo -S firewall-cmd --zone=public --add-service=tftp: [sudo] password for gns3user: 
sudo: no password was provided" in /home/gns3user/Automation/labs/test.py at line 58.

2021-09-30 19:15:06,151UTC: CRITICAL:root:
Type KeyboardInterrupt: "" in /home/gns3user/Automation/labs/test.py at line 31.

2021-09-30 19:20:42,954UTC: CRITICAL:root:
Type RuntimeError: "Cannot download startup-config from device using TFTP." in /home/gns3user/Automation/labs/lab000-combo.py at line 283.

2021-09-30 19:30:41,254UTC: CRITICAL:root:
Type RuntimeError: "Cannot download startup-config from device using TFTP." in /home/gns3user/Automation/labs/lab000-combo.py at line 285.

2021-09-30 19:32:01,989UTC: CRITICAL:root:
Type KeyboardInterrupt: "" in /home/gns3user/Automation/labs/lab000-combo.py at line 90.

2021-09-30 19:33:26,882UTC: CRITICAL:root:
Type RuntimeError: "Cannot download startup-config from device using TFTP." in /home/gns3user/Automation/labs/lab000-combo.py at line 286.

2021-09-30 20:05:58,496UTC: CRITICAL:root:
Type RuntimeError: "Cannot connect to console port." in /home/gns3user/Automation/labs/lab000-combo.py at line 113.

2021-09-30 20:11:44,848UTC: CRITICAL:root:
Type KeyboardInterrupt: "" in /home/gns3user/Automation/labs/lab000-combo.py at line 90.

2021-09-30 20:15:29,326UTC: CRITICAL:root:
Type IndexError: "tuple index out of range" in /home/gns3user/Automation/labs/lab000-combo.py at line 270.

2021-09-30 20:25:07,496UTC: CRITICAL:root:
Type RuntimeError: "Cannot download startup-config from device using TFTP." in /home/gns3user/Automation/labs/lab000-combo.py at line 284.

2021-09-30 20:29:22,751UTC: CRITICAL:root:
Type TIMEOUT: "Expected "Destination filename", found "ads""" in /home/gns3user/Automation/labs/lab000-combo.py at line 279.

2021-09-30 20:34:03,383UTC: CRITICAL:root:
Type RuntimeError: "Cannot download startup-config from device using TFTP." in /home/gns3user/Automation/labs/lab000-combo.py at line 283.

2021-10-02 04:26:51,427UTC: CRITICAL:root:
Type RuntimeError: "Cannot connect to console port." in /home/gns3user/Automation/labs/lab000-combo.py at line 110.

2021-10-06 14:45:14,015UTC: CRITICAL:root:
Type RuntimeError: "The filepath must start with /var/lib/tftpboot and the file to upload must be in that directory." in /home/gns3user/Automation/labs/lab000-combo.py at line 307.

2021-10-06 21:21:46,012UTC: CRITICAL:root:
Type RuntimeError: "Cannot download test.txt from device using TFTP." in /home/gns3user/Automation/labs/lab000-combo.py at line 284.

2021-10-24 19:24:25,262UTC: CRITICAL:root:
Type RuntimeError: "Unable to ping -c 4 255.255.255.0: PING 255.255.255.0 (255.255.255.0) 56(84) bytes of data.

--- 255.255.255.0 ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 3011ms" in /home/gns3user/Automation/labs/cisco_test.py at line 199.

2021-10-24 19:42:44,113UTC: CRITICAL:root:
Type RuntimeError: "Invalid port number." in /home/gns3user/Automation/labs/cisco_test.py at line 51.

2021-10-24 19:43:14,428UTC: CRITICAL:root:
Type RuntimeError: "Invalid port number." in /home/gns3user/Automation/labs/cisco_test.py at line 51.

2021-10-24 19:43:57,656UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found """ in /home/gns3user/Automation/labs/cisco_test.py at line 58.

2021-10-24 20:03:04,553UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found """ in /home/gns3user/Automation/labs/cisco.py at line 58.

2021-10-24 20:31:51,405UTC: CRITICAL:root:
Type ValueError: "Argument contains an invalid IP address: None" in /home/gns3user/Automation/labs/cisco.py at line 35.

2021-10-24 20:39:56,636UTC: CRITICAL:root:
Type AttributeError: "'bool' object has no attribute 'strip'" in /home/gns3user/Automation/labs/cisco.py at line 53.

2021-10-24 20:51:29,765UTC: CRITICAL:root:
Type TypeError: "assign_device_ip_addr() takes exactly 4 arguments (3 given)" in /home/gns3user/Automation/labs/cisco_test.py at line 32.

2021-10-24 21:01:03,098UTC: CRITICAL:root:
Type TypeError: "download_file_tftp() takes at least 3 arguments (2 given)" in /home/gns3user/Automation/labs/cisco_test.py at line 34.

2021-10-24 21:01:58,733UTC: CRITICAL:root:
Type ValueError: "Valid device file system (flash:, slot0:, etc.) not specified." in /home/gns3user/Automation/labs/cisco.py at line 236.

2021-10-25 01:01:12,531UTC: CRITICAL:root:
Type ValueError: "Argument contains an invalid IPv4 address: flash:/startup-config.bak" in /home/gns3user/Automation/labs/cisco.py at line 268.

2021-10-25 02:15:30,728UTC: CRITICAL:root:
Type TIMEOUT: "Expected "Error", found """ in /home/gns3user/Automation/labs/cisco.py at line 316.

2021-10-25 02:18:31,708UTC: CRITICAL:root:
Type TIMEOUT: "Expected "Error", found "(520 bytes/sec)"" in /home/gns3user/Automation/labs/cisco.py at line 316.

2021-10-25 02:20:25,935UTC: CRITICAL:root:
Type RuntimeError: "Cannot update startup configuration." in /home/gns3user/Automation/labs/cisco.py at line 322.

2021-10-25 02:22:14,759UTC: CRITICAL:root:
Type RuntimeError: "Cannot update startup configuration." in /home/gns3user/Automation/labs/cisco.py at line 322.

2021-10-26 02:30:17,563UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found """ in /home/gns3user/Automation/labs/cisco.py at line 53.

2021-10-26 02:34:08,810UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found """ in /home/gns3user/Automation/labs/cisco.py at line 53.

2021-10-26 02:59:26,883UTC: CRITICAL:root:
Type RuntimeError: "Cannot connect to console port." in /home/gns3user/Automation/labs/cisco_test.py at line 36.

2021-10-26 03:09:01,145UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found """ in /home/gns3user/Automation/labs/cisco.py at line 53.

2021-10-26 03:12:17,061UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found """ in /home/gns3user/Automation/labs/cisco.py at line 53.

2021-10-26 03:17:33,841UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found """ in /home/gns3user/Automation/labs/cisco.py at line 54.

2021-10-26 03:22:28,056UTC: CRITICAL:root:
Type RuntimeError: "Cannot upload /var/lib/tftpboot/startup-config-211026032043Z to device using TFTP." in /home/gns3user/Automation/labs/cisco.py at line 296.

2021-10-26 03:24:14,910UTC: CRITICAL:root:
Type RuntimeError: "Cannot update startup configuration." in /home/gns3user/Automation/labs/cisco.py at line 324.

2021-10-26 03:25:11,856UTC: CRITICAL:root:
Type RuntimeError: "Cannot upload /var/lib/tftpboot/startup-config-211026032506Z to device using TFTP." in /home/gns3user/Automation/labs/cisco.py at line 296.

2021-10-26 03:27:19,547UTC: CRITICAL:root:
Type RuntimeError: "Cannot connect to console port." in /home/gns3user/Automation/labs/cisco_test.py at line 37.

2021-10-26 03:32:15,096UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found """ in /home/gns3user/Automation/labs/cisco.py at line 54.

2021-10-26 03:38:32,116UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found """ in /home/gns3user/Automation/labs/cisco.py at line 54.

2021-10-26 03:38:52,770UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found """ in /home/gns3user/Automation/labs/cisco.py at line 54.

2021-10-26 03:39:07,723UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found """ in /home/gns3user/Automation/labs/cisco.py at line 54.

2021-10-26 03:42:32,378UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found """ in /home/gns3user/Automation/labs/cisco.py at line 54.

2021-10-26 03:43:16,609UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found "Trying 192.168.1.1..."" in /home/gns3user/Automation/labs/cisco.py at line 50.

2021-10-26 03:43:56,357UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found "Trying 192.168.1.1..."" in /home/gns3user/Automation/labs/cisco.py at line 52.

2021-10-26 03:45:13,722UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found "Trying 192.168.1.1..."" in /home/gns3user/Automation/labs/cisco.py at line 52.

2021-10-26 03:47:39,791UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found "Trying 192.168.1.1..."" in /home/gns3user/Automation/labs/cisco.py at line 52.

2021-10-26 03:48:44,241UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found "Trying 192.168.1.1..."" in /home/gns3user/Automation/labs/cisco.py at line 52.

2021-10-26 03:51:48,564UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found "Trying 192.168.1.1..."" in /home/gns3user/Automation/labs/cisco.py at line 52.

2021-10-26 04:19:31,177UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found """ in /home/gns3user/Automation/labs/cisco.py at line 56.

2021-10-26 04:23:07,901UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found """ in /home/gns3user/Automation/labs/cisco.py at line 56.

2021-10-26 04:24:03,842UTC: CRITICAL:root:
Type RuntimeError: "Cannot connect via Telnet." in /home/gns3user/Automation/labs/cisco.py at line 54.

2021-10-26 04:26:31,987UTC: CRITICAL:root:
Type RuntimeError: "Cannot connect via Telnet." in /home/gns3user/Automation/labs/cisco.py at line 54.

2021-10-26 04:31:47,973UTC: CRITICAL:root:
Type RuntimeError: "Cannot connect via Telnet." in /home/gns3user/Automation/labs/cisco.py at line 54.

2021-10-26 04:33:15,811UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found """ in /home/gns3user/Automation/labs/cisco.py at line 58.

2021-10-26 04:36:43,656UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found """ in /home/gns3user/Automation/labs/cisco.py at line 58.

2021-10-26 04:42:39,621UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found """ in /home/gns3user/Automation/labs/cisco.py at line 58.

2021-10-26 04:49:40,866UTC: CRITICAL:root:
Type TIMEOUT: "Expected EOF, found "Trying 192.168.1.1..."" in /home/gns3user/Automation/labs/cisco.py at line 52.

2021-10-26 04:54:16,519UTC: CRITICAL:root:
Type AttributeError: "'NoneType' object has no attribute 'expect_exact'" in /home/gns3user/Automation/labs/cisco_test.py at line 33.

2021-10-26 04:58:11,865UTC: CRITICAL:root:
Type AttributeError: "'NoneType' object has no attribute 'expect_exact'" in /home/gns3user/Automation/labs/cisco_test.py at line 33.

2021-10-26 05:04:01,104UTC: CRITICAL:root:
Type RuntimeError: "Cannot connect via console port." in /home/gns3user/Automation/labs/cisco_test.py at line 33.

2021-10-26 05:06:24,133UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found """ in /home/gns3user/Automation/labs/cisco.py at line 58.

2021-10-26 05:17:27,968UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found """ in /home/gns3user/Automation/labs/cisco.py at line 58.

2021-10-26 05:20:46,378UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found "Trying 192.168.1.1..."" in /home/gns3user/Automation/labs/cisco.py at line 60.

2021-10-27 20:07:05,684UTC: CRITICAL:root:
Type EOF: "Expected "R1>", found "Trying 192.168.1.1..."" in /home/gns3user/Automation/labs/cisco.py at line 60.

2021-10-27 20:09:42,173UTC: CRITICAL:root:
Type RuntimeError: "Cannot connect via Telnet." in /home/gns3user/Automation/labs/cisco.py at line 57.

2021-10-27 20:11:16,160UTC: CRITICAL:root:
Type OSError: "[Errno 9] Bad file descriptor" in /home/gns3user/Automation/labs/cisco.py at line 277.

2021-10-27 20:22:32,653UTC: CRITICAL:root:
Type RuntimeError: "Cannot connect via Telnet." in /home/gns3user/Automation/labs/cisco.py at line 57.

2021-10-27 20:30:58,715UTC: CRITICAL:root:
Type RuntimeError: "Cannot connect via Telnet." in /home/gns3user/Automation/labs/cisco.py at line 57.

2021-10-27 20:48:27,516UTC: CRITICAL:root:
Type RuntimeError: "Cannot upload /var/lib/tftpboot/startup-config-211027204822Z to device using TFTP." in /home/gns3user/Automation/labs/cisco.py at line 301.

2021-10-27 20:51:19,518UTC: CRITICAL:root:
Type TIMEOUT: "Expected "Error", found "ation filename [startup-config.bak]? "" in /home/gns3user/Automation/labs/cisco.py at line 322.

2021-10-27 20:55:38,558UTC: CRITICAL:root:
Type RuntimeError: "Cannot connect via Telnet." in /home/gns3user/Automation/labs/cisco.py at line 57.

2021-10-27 21:02:26,605UTC: CRITICAL:root:
Type RuntimeError: "Cannot connect via Telnet." in /home/gns3user/Automation/labs/cisco.py at line 57.

2021-10-27 21:04:11,978UTC: CRITICAL:root:
Type RuntimeError: "Cannot connect via Telnet." in /home/gns3user/Automation/labs/cisco.py at line 57.

2021-10-27 23:54:34,928UTC: CRITICAL:root:
Type RuntimeError: "Cannot connect via console port." in /home/gns3user/Automation/labs/cisco_test.py at line 31.

2021-10-28 00:49:22,867UTC: CRITICAL:root:
Type OSError: "[Errno 9] Bad file descriptor" in /home/gns3user/Automation/labs/cisco.py at line 77.

2021-10-28 01:22:23,028UTC: CRITICAL:root:
Type TIMEOUT: "Expected "enable, found """ in /home/gns3user/Automation/labs/cisco.py at line 103.

2021-10-28 01:26:07,936UTC: CRITICAL:root:
Type TIMEOUT: "Expected "R1>", found "otocol on Interface FastEthernet0/1, changed state to down"" in /home/gns3user/Automation/labs/cisco.py at line 64.

2021-10-28 01:29:05,085UTC: CRITICAL:root:
Type TIMEOUT: "Expected "R1>", found "ilable"" in /home/gns3user/Automation/labs/cisco.py at line 64.

2021-10-28 01:34:23,252UTC: CRITICAL:root:
Type TIMEOUT: "Expected "R1>", found "able"" in /home/gns3user/Automation/labs/cisco.py at line 64.

2021-10-28 02:17:52,252UTC: WARNING:root:Script /home/gns3user/Automation/labs/lab_utils.py cannot be run independently from this application.
2021-10-28 02:24:21,156UTC: CRITICAL:root:
Type RuntimeError: "Cannot connect via console port." in /home/gns3user/Automation/labs/cisco_test.py at line 30.

2021-10-28 02:39:30,234UTC: CRITICAL:root:
Type TIMEOUT: "Expected "R1>", found "vailable





Press RETURN to get started.






User Access Verification

Password: "" in /home/gns3user/Automation/labs/cisco.py at line 64.

2021-10-28 02:41:11,900UTC: CRITICAL:root:
Type TIMEOUT: "Expected "R1>", found " now available





Press RETURN to get started.



User Access Verification

Password: "" in /home/gns3user/Automation/labs/cisco.py at line 64.

2021-10-28 02:46:21,421UTC: CRITICAL:root:
Type TIMEOUT: "Expected "R1>", found "ilable......Press RETURN to get started.........User Access Verification..Password: ."" in /home/gns3user/Automation/labs/cisco.py at line 64.

2021-10-28 02:48:51,457UTC: CRITICAL:root:
Type TIMEOUT: "Expected "R1>", found "    Press RETURN to get started.             User Access Verification  Password:  "" in /home/gns3user/Automation/labs/cisco.py at line 64.

2021-10-28 02:55:26,256UTC: CRITICAL:root:
Type TIMEOUT: "Expected "R1>", found "Press RETURN to get started.User Access VerificationPassword: "" in /home/gns3user/Automation/labs/cisco.py at line 64.

2021-10-28 02:59:30,984UTC: CRITICAL:root:
Type TIMEOUT: "Expected "R1>", found "  Press RETURN to get started.                                User Access Verification    Password:  "" in /home/gns3user/Automation/labs/cisco.py at line 64.

2021-10-28 03:02:30,793UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string:     0: "R1>"     1: "R1#"     2: "R1(config)"     3: "R1(config-if)"     4: "R1(config-router)"     5: "R1(config-line)" , found "otocol on Interface FastEthernet0/1, changed state to down    User Access Verification    Password:  "" in /home/gns3user/Automation/labs/cisco.py at line 64.

2021-10-28 03:05:54,288UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string:     0: "R1>"     1: "R1#"     2: "R1(config)"     3: "R1(config-if)"     4: "R1(config-router)"     5: "R1(config-line)" , found "      Press RETURN to get started.                            User Access Verification    Password:  "" in /home/gns3user/Automation/labs/cisco.py at line 64.

2021-10-28 03:07:55,103UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string:   0: "R1>"   1: "R1#"   2: "R1(config)"   3: "R1(config-if)"   4: "R1(config-router)"   5: "R1(config-line)" , found "ow available      Press RETURN to get started.     User Access Verification  Password: "" in /home/gns3user/Automation/labs/cisco.py at line 64.

2021-10-28 03:20:19,540UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: "R1>" 1: "R1#" 2: "R1(config)" 3: "R1(config-if)" 4: "R1(config-router)" 5: "R1(config-line)" , found "otocol on Interface FastEthernet0/1, changed state to down User Access Verification Password: "" in /home/gns3user/Automation/labs/cisco.py at line 64.

2021-10-28 03:26:06,113UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: "R1>" 1: "R1#" 2: "R1(config)" 3: "R1(config-if)" 4: "R1(config-router)" 5: "R1(config-line)" , found " available Press RETURN to get started. User Access Verification Password:" in /home/gns3user/Automation/labs/cisco.py at line 64.

2021-10-28 03:30:38,678UTC: CRITICAL:root:
Type EOF: "Expected searcher_string: 0: "R1>" 1: "R1#" 2: "R1(config)" 3: "R1(config-if)" 4: "R1(config-router)" 5: "R1(config-line)" , found "" in /home/gns3user/Automation/labs/cisco.py at line 101.

2021-10-28 03:31:09,001UTC: CRITICAL:root:
Type EOF: "Expected searcher_string: 0: "R1>" 1: "R1#" 2: "R1(config)" 3: "R1(config-if)" 4: "R1(config-router)" 5: "R1(config-line)" , found "" in /home/gns3user/Automation/labs/cisco.py at line 101.

2021-10-28 03:37:18,084UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: "R1>" 1: "R1#" 2: "R1(config)" 3: "R1(config-if)" 4: "R1(config-router)" 5: "R1(config-line)" , found "otocol on Interface FastEthernet0/1, changed state to down User Access Verification Password:" in /home/gns3user/Automation/labs/cisco.py at line 101.

2021-10-28 03:57:43,025UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: " R1# R1# R1#" , found " Press RETURN to get started. User Access Verification Password:" in /home/gns3user/Automation/labs/cisco.py at line 106.

2021-10-28 04:00:10,311UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: " R1# R1# R1#" , found " Press RETURN to get started. User Access Verification Password:" in /home/gns3user/Automation/labs/cisco.py at line 106.

2021-10-28 04:02:22,539UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: " R1# R1# R1#" , found " now available Press RETURN to get started. User Access Verification Password:" in /home/gns3user/Automation/labs/cisco.py at line 106.

2021-10-28 04:08:12,524UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: "R1#" , found "" in /home/gns3user/Automation/labs/cisco.py at line 104.

2021-10-28 04:13:20,531UTC: CRITICAL:root:
Type IndexError: "list index out of range" in /home/gns3user/Automation/labs/cisco.py at line 111.

2021-10-28 04:18:03,458UTC: CRITICAL:root:
Type IndexError: "list index out of range" in /home/gns3user/Automation/labs/cisco.py at line 111.

2021-10-28 04:20:12,495UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: "Press RETURN to get started" 1: "Password:" 2: EOF 3: "R1>" 4: "R1#" 5: "R1(config)" 6: "R1(config-if)" 7: "R1(config-router)" 8: "R1(config-line)" , found "x HW Table --More-- R1#show q zz XDTUEMRBM pp" in /home/gns3user/Automation/labs/cisco.py at line 59.

2021-10-28 04:24:44,003UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: "Press RETURN to get started" 1: "Password:" 2: EOF 3: "R1>" 4: "R1#" 5: "R1(config)" 6: "R1(config-if)" 7: "R1(config-router)" 8: "R1(config-line)" , found "00:00:05.623: %LINEPROTO-5-UPDOWN: Line protocol on Interface FastEthernet0/1, changed state to down" in /home/gns3user/Automation/labs/cisco.py at line 59.

2021-10-28 04:28:00,609UTC: CRITICAL:root:
Type IndexError: "list index out of range" in /home/gns3user/Automation/labs/cisco.py at line 111.

2021-10-28 04:32:47,832UTC: CRITICAL:root:
Type IndexError: "list index out of range" in /home/gns3user/Automation/labs/cisco.py at line 111.

2021-10-28 04:37:01,829UTC: CRITICAL:root:
Type IndexError: "list index out of range" in /home/gns3user/Automation/labs/cisco.py at line 111.

2021-10-28 14:52:28,229UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: "R1>" 1: "R1#" 2: "R1(config)" 3: "R1(config-if)" 4: "R1(config-router)" 5: "R1(config-line)" , found "# R1(config)#" in /home/gns3user/Automation/labs/cisco.py at line 379.

2021-10-28 15:00:46,583UTC: CRITICAL:root:
Type IndexError: "list index out of range" in /home/gns3user/Automation/labs/cisco.py at line 111.

2021-10-28 15:08:26,154UTC: CRITICAL:root:
Type IndexError: "list index out of range" in /home/gns3user/Automation/labs/cisco.py at line 112.

2021-10-28 15:13:15,462UTC: CRITICAL:root:
Type IndexError: "list index out of range" in /home/gns3user/Automation/labs/cisco.py at line 112.

2021-10-28 15:15:52,746UTC: CRITICAL:root:
Type IndexError: "list index out of range" in /home/gns3user/Automation/labs/cisco.py at line 113.

2021-10-28 15:20:36,512UTC: CRITICAL:root:
Type IndexError: "list index out of range" in /home/gns3user/Automation/labs/cisco.py at line 113.

2021-10-28 15:27:42,273UTC: CRITICAL:root:
Type IndexError: "list index out of range" in /home/gns3user/Automation/labs/cisco.py at line 115.

2021-10-28 15:29:06,239UTC: CRITICAL:root:
Type IndexError: "list index out of range" in /home/gns3user/Automation/labs/cisco.py at line 116.

2021-10-28 15:34:07,790UTC: CRITICAL:root:
Type IndexError: "list index out of range" in /home/gns3user/Automation/labs/cisco.py at line 116.

2021-10-28 15:39:34,944UTC: CRITICAL:root:
Type IndexError: "list index out of range" in /home/gns3user/Automation/labs/cisco.py at line 113.

2021-10-28 15:53:50,070UTC: CRITICAL:root:
Type IndexError: "list index out of range" in /home/gns3user/Automation/labs/cisco.py at line 115.

2021-10-28 15:57:15,999UTC: CRITICAL:root:
Type IndexError: "list index out of range" in /home/gns3user/Automation/labs/cisco.py at line 115.

2021-10-28 16:01:23,448UTC: CRITICAL:root:
Type IndexError: "list index out of range" in /home/gns3user/Automation/labs/cisco.py at line 123.

2021-10-28 16:05:20,581UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's name." in /home/gns3user/Automation/labs/cisco.py at line 123.

2021-10-28 16:06:33,998UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's name." in /home/gns3user/Automation/labs/cisco.py at line 123.

2021-10-28 16:08:43,377UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's name." in /home/gns3user/Automation/labs/cisco.py at line 125.

2021-10-28 16:12:47,158UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's name." in /home/gns3user/Automation/labs/cisco.py at line 127.

2021-10-28 16:14:19,171UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's name." in /home/gns3user/Automation/labs/cisco.py at line 127.

2021-10-28 16:17:09,518UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's name." in /home/gns3user/Automation/labs/cisco.py at line 127.

2021-10-28 16:22:07,067UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's name." in /home/gns3user/Automation/labs/cisco.py at line 123.

2021-10-28 16:23:27,999UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 116.

2021-10-28 16:30:45,818UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 116.

2021-10-28 16:38:19,622UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 116.

2021-10-28 16:48:18,342UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 117.

2021-10-28 16:53:10,788UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 117.

2021-10-28 17:07:03,587UTC: CRITICAL:root:
Type IOError: "[Errno 2] No such file or directory: '/home/gns3user/Automation/labs/c3745.log'" in /home/gns3user/Automation/labs/cisco_test.py at line 27.

2021-10-28 17:09:05,337UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 117.

2021-10-28 19:23:01,482UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: EOF 1: "Press RETURN to get started" 2: "Password:" 3: "R1>" 4: "R1#" 5: "R1(config)#" 6: "R1(config-if)#" 7: "R1(config-router)#" 8: "R1(config-line)#" , found "." in /home/gns3user/Automation/labs/cisco.py at line 59.

2021-10-28 19:33:57,682UTC: CRITICAL:root:
Type RuntimeError: "Cannot connect via Telnet." in /home/gns3user/Automation/labs/cisco.py at line 61.

2021-10-28 19:35:01,618UTC: CRITICAL:root:
Type RuntimeError: "Cannot connect via Telnet." in /home/gns3user/Automation/labs/cisco.py at line 61.

2021-10-28 19:35:33,625UTC: CRITICAL:root:
Type RuntimeError: "Cannot connect via Telnet." in /home/gns3user/Automation/labs/cisco.py at line 61.

2021-10-28 19:48:00,094UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 110.

2021-10-28 19:50:29,836UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 110.

2021-10-28 19:58:28,961UTC: CRITICAL:root:
Type RuntimeError: "Unable to sudo firewall-cmd --zone=public --add-port=23/tcp: [sudo] password for gns3user:" in /home/gns3user/Automation/labs/cisco.py at line 50.

2021-10-28 19:59:05,464UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 110.

2021-10-28 20:15:01,833UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 110.

2021-10-28 20:18:24,162UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 111.

2021-10-28 20:18:56,838UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 111.

2021-10-28 20:26:32,152UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 111.

2021-10-28 21:17:49,458UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 116.

2021-10-28 21:22:16,053UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: EOF , found "ftware, 3700 Software (C3745-ADVENTERPRISEK9-M), Version 12.4(25d), RELEASE SOFTWARE (fc1) R1# R1#" in /home/gns3user/Automation/labs/cisco.py at line 111.

2021-10-28 21:28:31,609UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 116.

2021-10-28 22:07:57,061UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 116.

2021-10-29 01:46:47,481UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: EOF 1: "Press RETURN to get started" 2: "Password:" 3: "R1>" 4: "R1#" 5: "R1(config)#" 6: "R1(config-if)#" 7: "R1(config-router)#" 8: "R1(config-line)#" , found "." in /home/gns3user/Automation/labs/cisco.py at line 63.

2021-10-29 01:51:35,000UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 123.

2021-10-29 01:52:51,107UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 123.

2021-10-29 02:09:59,267UTC: CRITICAL:root:
Type TypeError: "object of type 'NoneType' has no len()" in /home/gns3user/Automation/labs/cisco.py at line 79.

2021-10-29 02:20:26,201UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 119.

2021-10-29 02:32:57,388UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: ";START HERE (211029023150Z) " , found "wn command or computer name, or unable to find computer address R1#;START HERE (211029023150Z) R1#" in /home/gns3user/Automation/labs/cisco.py at line 114.

2021-10-29 02:35:39,060UTC: CRITICAL:root:
Type TypeError: "cannot concatenate 'str' and 'int' objects" in /home/gns3user/Automation/labs/cisco.py at line 114.

2021-10-29 03:28:56,696UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 119.

2021-10-29 03:46:34,308UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's name." in /home/gns3user/Automation/labs/cisco.py at line 126.

2021-10-29 03:59:54,664UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 119.

2021-10-29 04:00:16,509UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 119.

2021-10-29 04:01:30,343UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: "R1>" 1: "R1#" 2: "R1(config)#" 3: "R1(config-if)#" 4: "R1(config-router)#" 5: "R1(config-line)#" , found ". User Access Verification Password:" in /home/gns3user/Automation/labs/cisco.py at line 114.

2021-10-29 04:09:10,476UTC: CRITICAL:root:
Type TypeError: "bad operand type for unary +: 'list'" in /home/gns3user/Automation/labs/cisco.py at line 114.

2021-10-29 04:11:18,096UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: "R1#" , found " R1 con0 is now available Press RETURN to get started." in /home/gns3user/Automation/labs/cisco.py at line 116.

2021-10-29 04:23:46,138UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 119.

2021-10-29 04:33:53,533UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 119.

2021-10-29 18:33:41,985UTC: CRITICAL:root:
Type RuntimeError: "Unable to sudo systemctl stop tftp: [sudo] password for gns3user: 
Sorry, try again.
[sudo] password for gns3user: 
Sorry, try again.
[sudo] password for gns3user: 
sudo: 3 incorrect password attempts" in /home/gns3user/Automation/labs/cisco.py at line 328.

2021-10-29 18:53:15,983UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: "Error" 1: "[OK]" , found " R1 con0 is now available Press RETURN to get started." in /home/gns3user/Automation/labs/cisco.py at line 346.

2021-10-29 18:55:56,887UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: "Error" 1: "[OK]" , found " Press RETURN to get started. User Access Verification Password:" in /home/gns3user/Automation/labs/cisco.py at line 346.

2021-10-29 19:01:34,233UTC: CRITICAL:root:
Type RuntimeError: "Cannot connect via Telnet." in /home/gns3user/Automation/labs/cisco.py at line 71.

2021-10-29 19:03:11,361UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: "Address or name of remote host" , found "029190239 Z ^ % Invalid input detected at '^' marker. R1(config)#" in /home/gns3user/Automation/labs/cisco.py at line 264.

2021-10-30 00:36:50,186UTC: CRITICAL:root:
Type RuntimeError: "Cannot get the device's software version." in /home/gns3user/Automation/labs/cisco.py at line 136.

2021-10-30 01:12:16,273UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: EOF , found "OS Software, 3700 Software (C3745-ADVENTERPRISEK9-M), Version 12.4(25d), RELEASE SOFTWARE (fc1) R1#" in /home/gns3user/Automation/labs/cisco.py at line 135.

2021-10-30 01:17:59,104UTC: CRITICAL:root:
Type IndexError: "list index out of range" in /home/gns3user/Automation/labs/cisco.py at line 136.

2021-10-30 01:24:59,349UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_re: 0: EOF , found "OS Software, 3700 Software (C3745-ADVENTERPRISEK9-M), Version 12.4(25d), RELEASE SOFTWARE (fc1) R1#" in /home/gns3user/Automation/labs/cisco.py at line 135.

2021-10-30 01:37:40,134UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_re: 0: EOF , found "OS Software, 3700 Software (C3745-ADVENTERPRISEK9-M), Version 12.4(25d), RELEASE SOFTWARE (fc1) R1#" in /home/gns3user/Automation/labs/cisco.py at line 135.

2021-10-31 04:06:40,718UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_re: 0: EOF , found "OS Software, 3700 Software (C3745-ADVENTERPRISEK9-M), Version 12.4(25d), RELEASE SOFTWARE (fc1) R1#" in /home/gns3user/Automation/labs/cisco.py at line 152.

2021-10-31 04:17:36,916UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: "04:17:05 UTC Sun Oct 31 2021, configured from console by console" , found "ARE (fc1) R1>clock set 04:17:05 31 Oct 2021 ^ % Invalid input detected at '^' marker. R1>" in /home/gns3user/Automation/labs/cisco.py at line 155.

2021-10-31 04:20:14,941UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: "04:19:43 UTC Sun Oct 31 2021, configured from console by console" , found "fc1) R1> R1>clock set 04:19:43 31 Oct 2021 ^ % Invalid input detected at '^' marker. R1>" in /home/gns3user/Automation/labs/cisco.py at line 157.

2021-10-31 04:29:26,675UTC: CRITICAL:root:
Type AttributeError: "Cisco instance has no attribute 'pexpect'" in /home/gns3user/Automation/labs/cisco.py at line 97.

2021-10-31 04:31:46,892UTC: CRITICAL:root:
Type TIMEOUT: "Expected searcher_string: 0: "04:31:15 UTC Sun Oct 31 2021, configured from console by console" , found "> R1>enable Password: Password: Password: % Bad secrets R1>enable Password: Password:" in /home/gns3user/Automation/labs/cisco.py at line 157.

2021-10-31 04:33:43,610UTC: CRITICAL:root:
Type IndexError: "list index out of range" in /home/gns3user/Automation/labs/cisco.py at line 172.

